version: '2'

services:
  elasticsearch:
    image: projectmirror/elasticsearch:1.0
    volumes:
      - /var/lib/projectmirror/analytics/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - /var/lib/projectmirror/analytics/elasticsearch/data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk

  logstash:
    image: projectmirror/logstash:1.0
    volumes:
      - /var/lib/projectmirror/analytics/logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - /var/lib/projectmirror/analytics/logstash/pipeline:/usr/share/logstash/pipeline:ro
    ports:
      - "5000:5000"
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk
    depends_on:
      - elasticsearch

  kibana:
    image: projectmirror/logstash:1.0
    volumes:
      - /var/lib/projectmirror/analytics/kibana/config/:/usr/share/kibana/config:ro
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch

  webapp:
    image: projectmirror/webapp:1.0
    ports:
      - "8000:8000"
    restart: on-failure

networks:
  elk:
    driver: bridge
