version: '2'

services:
  webapp:
    build:
      context: webapp/
    image: projectmirror/webapp:1.0
    volumes:
      - ./webapp:/webapp
      - ./webapp/data:/var/lib/data
    ports:
      - "8000:8000"
    networks:
      - elk
    restart: on-failure

networks:
  elk:
    driver: bridge
